//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zuper_Mart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutU
    {
        public int AboutUsID { get; set; }
        public string StorePURL { get; set; }
        public string BrandPURL { get; set; }
        public string AboutDesc { get; set; }
        public string FounderPURL { get; set; }
        public string FounderName { get; set; }
        public string FounderDesc { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string WhatsApp { get; set; }
        public string LocationLink { get; set; }
        public string FBURL { get; set; }
        public string WAURL { get; set; }
        public string YTURL { get; set; }
        public string INSTAURL { get; set; }
    }
}
