//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zuper_Mart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSpecification
    {
        public int ProductSpecificationSID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string Specifications { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
