//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zuper_Mart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMember
    {
        public int TeamMemberID { get; set; }
        public string MemName { get; set; }
        public string MemStudentID { get; set; }
        public string MemFBlink { get; set; }
        public string MemWAlink { get; set; }
        public string MemLIlink { get; set; }
        public string MemGHlink { get; set; }
        public string MemImgUrl { get; set; }
        public string status { get; set; }
    }
}
